apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "foo.local"
    - "bar.local"
  - ip: "10.1.2.3"
    hostnames:
    - "foo.remote"
    - "bar.remote"
  containers:
  - name: cat-hosts
    image: busybox:latest
    command:
    - cat
    args:
    - "/etc/hosts"

# kubectl apply -f network/hostaliases-pod.yaml 
# kubectl get pods --output=wide
# kubectl logs hostaliases-pod