apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

# kubectl apply -f deployment/nginx-deployment.yaml
# kubectl get pods --show-labels
# kubectl get deployments
# kubectl get deployment --show-labels
# kubectl get deployment 


# kubectl rollout status deployment/nginx-deployment
# kubectl get rs
# kubectl --record deployment.apps/nginx-deployment set image deployment.v1.apps/nginx-deployment nginx=nginx:1.16.1

# kubectl delete pod nginx-deployment-7b45d69949-4cfxz

# kubectl edit deployment.v1.apps/nginx-deployment -- update the nginx version
# kubectl rollout status deployment/nginx-deployment
# kubectl describe deployments

# kubectl rollout status deployment/nginx-deployment
# kubectl set image deployment.v1.apps/nginx-deployment nginx=nginx:1.161 --record=true
# kubectl get rs
# kubectl get pods
# kubectl describe deployment

# kubectl set image deployment.v1.apps/nginx-deployment nginx=nginx:1.14.2 --record=true
# kubectl rollout history deployment.v1.apps/nginx-deployment
# kubectl rollout history deployment.v1.apps/nginx-deployment --revision=2
# kubectl get pods -o wide
# kubectl rollout undo deployment.v1.apps/nginx-deployment --to-revision=4
# kubectl get pods -o wide
# kubectl get all
# kubectl describe deployment nginx-deployment

# kubectl scale deployment.v1.apps/nginx-deployment --replicas=5
# kubectl get pods -o wide
# kubectl autoscale deployment.v1.apps/nginx-deployment --min=5 --max=10 --cpu-percent=80
# kubectl get deploy

# kubectl rollout pause deployment.v1.apps/nginx-deployment
# kubectl set image deployment.v1.apps/nginx-deployment nginx=nginx:latest
# kubectl rollout history deployment.v1.apps/nginx-deployment

# kubectl set resources deployment.v1.apps/nginx-deployment -c=nginx --limits=cpu=200m,memory=512Mi

# kubectl get deployment nginx-deployment -o yaml

# kubectl get deployment --show-labels
# kubectl delete deployment nginx-deployment
# kubectl get all
# kubectl get hpa
# kubectl delete hpa nginx-deployment
# kubectl get all