apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret


# kubectl apply -f secret/ex1/node-pod.yaml
# kubectl get pod
# kubectl exec -it secret-test-pod sh
# cd /etc/secret-volume
# cat PASSWORD
# cat USER_NAME
# kubectl delete pod secret-test-pod 
