apiVersion: v1
kind: Secret
metadata:
  name: test-secret
stringData:
  username: admin
  password: t0p-Secret

# kubectl apply -f secret/ex1/secrert.yaml 
# kubectl get secret
# describe secret mysecret