apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
      - containerPort: 80

# kubectl create -f nginx.pod1.yml --save-config
# kubectl get pod my-nginx -o yaml/json
# kubectl describe pod my-nginx
# kubectl apply -f nginx-pod1.yml
# kubectl exec my-nginx -it sh
# kubectl edit -f nginx.pod1.yml 
# kubectl delete -f nginx.pod1.yml 