apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine


# kubectl create -f nginx.pod.yml --validate=true
# kubectl delete pods --all
# kubectl apply -f nginx.pod.yml 
# kubectl get pods --output=wide
# kubectl delete pods --all

