apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"

# kubectl apply -f pods/nginx-pod-limit.yaml 
# kubetl get pod -o wide
# kubectl delete pod my-nginx-cpu