apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"


# kubectl apply -f configmap/configmap1.yaml   
# kubectl get cm
# kubectl describe cm game-demo